# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches:
  pull_request:
    branches:

jobs:
  test:
    if: "!contains(toJson(github.event.commits), '[skip ci]')"
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [10.13.0, 10.x, 12.13.0, 12.x, 14.15.0, 14.x]
        ts-version: [4.1.2]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }} & Typescript ${{ matrix.ts-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
        yarn install
        yarn add typescript@${{ matrix.ts-version }} --dev
    - run: yarn test
    - name: Coverage
      uses: codecov/codecov-action@v1
      if: matrix.node-version == '12.13.0' && matrix.ts-version == '4.1.2' && github.ref == 'refs/heads/master' && matrix.os == 'ubuntu-latest'
  publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn install
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
